---
services:
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    container_name: bebe-database
    environment:
      POSTGRES_DB: bebe
      # You should definitely change the password in production
      POSTGRES_PASSWORD: bebe
      POSTGRES_USER: bebe
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-bebe}", "-U", "${POSTGRES_USER:-bebe}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw
  php:
    container_name: bebe-php
    restart: unless-stopped
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}, php:80
      DEFAULT_URI: https://${SERVER_NAME:-localhost}:${HTTPS_PORT:-443}
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!sdfsdfsdfzazeazesdfsdf!}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!sdfdsfdfdfvbnvbnvbn!}
      # Run "composer require symfony/orm-pack" to install and configure Doctrine ORM
      DATABASE_URL: postgresql://${POSTGRES_USER:-bebe}:${POSTGRES_PASSWORD:-bebe}@database:5432/${POSTGRES_DB:-bebe}?serverVersion=${POSTGRES_VERSION:-16}&charset=${POSTGRES_CHARSET:-utf8}
      # Run "composer require symfony/mercure-bundle" to install and configure the Mercure integration
      MERCURE_URL: ${CADDY_MERCURE_URL:-http://php/.well-known/mercure}
      MERCURE_PUBLIC_URL: ${CADDY_MERCURE_PUBLIC_URL:-https://${SERVER_NAME:-localhost}:${HTTPS_PORT:-443}/.well-known/mercure}
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET:-!sdfsdfsdfsdfsdf5555!}
      ###> dunglas/symfony-docker ###
      # Next lines are only used during initial installation
      # This block will remove itself after the installation
      SYMFONY_VERSION: ${SYMFONY_VERSION:-}
      STABILITY: ${STABILITY:-stable}
      ###< dunglas/symfony-docker ###
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - name: http
        target: 80
        published: ${HTTP_PORT:-8000}
        protocol: tcp
      - name: https
        target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      - name: http3
        target: 443
        published: ${HTTP3_PORT:-8443}
        protocol: udp
    depends_on:
      database:
        condition: service_healthy
  ###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    container_name: bebe-mailer
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###
# Mercure is installed as a Caddy module, prevent the Flex recipe from installing another service
###> symfony/mercure-bundle ###

volumes:
  caddy_data:
  caddy_config:
  database_data:
